### ISSUE TITLE
Get DB writing working with Denali

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-help-wanted-backend#3]
Right now Denali's ORM system is sketched out but hasn't been fully built.  This adapter (https://github.com/denali-js/denali-node-orm2) needs help / testing in order to allow this app to function.  This app (primarily the web hook adapter) will need the ability to do all CRUD operations (deletions are triggered by Github), so we'll need to flesh that out in order to get this running smoothly.

**Comment by acorncom** [comment]
@knownasilya Per Dave, you've been working on a Knex adapter for Denali?  Should we hack on that instead of the one above?

**Comment by knownasilya** [comment]
Sure, I'll push it up later tonight.

**Comment by knownasilya** [comment]
Forgot I already pushed it up https://github.com/knownasilya/denali-knex

It's still basically a scaffolded project. Left off debugging why the resulting object during initializing `knex` is `undefined`.. Debugging didn't work, but it does now at least with `denali test --debug`

**Comment by acorncom** [comment]
Once this PR (https://github.com/denali-js/denali-node-orm2/pulls) gets merged, we'll want to start using a stable version of the add-on and then this issue can be closed.
